model_path = ""
wandb = ""
proj_dir = "out"
data_file = ""
data_type = "binidx"
vocab_size = 0
my_exit = 99999999
my_exit_tokens = 0
magic_prime = 0
lora_load = ""
pissa_load = ""
pissa_init = ""
disha_load = ""
quant_path = ""
my_pile_version = 1
my_pile_stage = 0
my_pile_shift = -1
my_pile_edecay = 0
