model_path = ""
wandb = ""
proj_dir = "out/test"
data_file = "/public/home/ssjxzkz/Datasets/lm/OptimalScale_ClimbLab/mmap/block_blm_data_device_0"
#data_file = "/mnt/g/Projects/MachineLearning/block-blm/data/block_blm_partial_data_device_0"
data_type = "binidx"
vocab_size = 256
my_exit = 99999999
my_exit_tokens = 4994480372591
magic_prime = 1219355507
#my_exit_tokens = 16332356
#magic_prime = 3947
lora_load = ""
pissa_load = ""
pissa_init = ""
disha_load = ""
quant_path = ""
my_pile_version = 1
my_pile_stage = 2
my_pile_shift = -1
my_pile_edecay = 0

