random_seed = -1
epoch_steps = 1
epoch_count = 999999
epoch_begin = 0
epoch_save = 10
ctx_len = 4096
micro_bsz = 210
accelerator = "gpu"
strategy = "deepspeed_stage_2"
devices = 1
num_nodes = 6
precision = "bf16"
accumulate_grad_batches = 1
lr_init = 1e-3
lr_final = 1e-4
warmup_steps = 10
beta1 = 0.9
beta2 = 0.99
adam_eps = 1e-18
weight_decay = 0.001
weight_decay_final = -1.0
grad_cp = 1
layerwise_lr = 1
optim = "none"
lr_schedule = "cos"
gradient_clip_val = 1.0
peft = "none"
train_parts = [ "time", "ln",]
dataload = "pad"
chunk_ctx = 512
loss_mask = "none"
data_shuffle = 1
avg_loss = 0
sft_split = "train"
ds_bucket_mb = 200
my_sample_len = 0
my_qa_mask = 0
my_random_steps = 0
my_ffn_shift = 1
my_att_shift = 1
my_testing = "x070"
fla = false
train_type = "none"
load_partial = 0
quant = "none"

[lora_config]
lora_load = ""
lora_r = 8
lora_alpha = 32
lora_dropout = 0.01

[pissa_config]
pissa_load = ""
pissa_init = ""
pissa_r = 8
svd_niter = 4

[disha_config]
mode = "mode"
load = ""
r = 64

[mask_id]
mask0 = "0"
mask1 = "1"
