model_path = ""
wandb = ""
proj_dir = "out/L6-D256-x070"
data_file = "/public/home/ssjxzkz/Datasets/lm/OptimalScale_ClimbLab/mmap/block_blm_data_device_0"
data_type = "binidx"
vocab_size = 256
my_exit = 99999999
my_exit_tokens = 4994480372591
magic_prime = 1219355507
lora_load = ""
pissa_load = ""
pissa_init = ""
disha_load = ""
quant_path = ""
my_pile_version = 1
my_pile_stage = 0
my_pile_shift = -1
my_pile_edecay = 0
